create table
  public."URL" (
    id bigint generated by default as identity not null,
    "ShortenedURL" character varying not null,
    "OriginalURL" character varying not null,
    "CreatedOn" timestamp with time zone not null default now(),
    "IPAddress" character varying not null,
    constraint URL_pkey primary key (id)
  ) tablespace pg_default;

